#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: cello-analytics
  default_branch: main
  archived: true
  private: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
